// Logo and branding
export const COMPANY_NAME = 'Frontier Fungi';
export const FREE_SHIPPING_THRESHOLD = 75;

// Navigation items
export const NAV_ITEMS = [
  { name: 'Shop', href: '/shop' },
  { name: 'Culture Library', href: '/culture-library' },
  { name: 'Learn', href: '/learn' },
  { name: 'Connect', href: '#contact' },
];

// Mushroom cultures
export const MUSHROOM_CULTURES = [
  {
    id: 'golden-oyster',
    name: 'Golden Oyster',
    description: 'Bright yellow clusters with a delicate flavor and aroma',
    price: 18.99,
    difficulty: 'Beginner Friendly',
    image: 'https://images.pexels.com/photos/15016561/pexels-photo-15016561.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '65-75°F',
    fruiting_time: '10-14 days',
    yield: 'High',
    substrate: 'Straw, hardwood sawdust, coffee grounds',
    flavor_profile: 'Mild, subtly sweet with nutty undertones',
  },
  {
    id: 'lions-mane',
    name: 'Lion\'s Mane',
    description: 'Unique texture with seafood-like flavor and health benefits',
    price: 22.99,
    difficulty: 'Intermediate',
    image: 'https://images.pexels.com/photos/15016562/pexels-photo-15016562.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '65-70°F',
    fruiting_time: '14-21 days',
    yield: 'Medium',
    substrate: 'Hardwood sawdust, supplemented sawdust',
    flavor_profile: 'Delicate seafood-like flavor similar to crab or lobster',
  },
  {
    id: 'shiitake',
    name: 'Shiitake',
    description: 'Rich umami flavor perfect for Asian cuisine',
    price: 19.99,
    difficulty: 'Beginner Friendly',
    image: 'https://images.pexels.com/photos/1627825/pexels-photo-1627825.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '55-75°F',
    fruiting_time: '7-14 days',
    yield: 'High',
    substrate: 'Hardwood logs, supplemented sawdust',
    flavor_profile: 'Rich, earthy, umami flavor that intensifies when dried',
  },
  {
    id: 'blue-oyster',
    name: 'Blue Oyster',
    description: 'Beautiful bluish-grey caps with mild, earthy flavor',
    price: 17.99,
    difficulty: 'Beginner Friendly',
    image: 'https://images.pexels.com/photos/6260003/pexels-photo-6260003.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '45-65°F',
    fruiting_time: '7-14 days',
    yield: 'Very High',
    substrate: 'Straw, coffee grounds, hardwood sawdust',
    flavor_profile: 'Mild and earthy with subtle anise notes',
  },
  {
    id: 'pearl-oyster',
    name: 'Pearl Oyster',
    description: 'Classic white oyster variety with excellent yields',
    price: 16.99,
    difficulty: 'Beginner Friendly',
    image: 'https://images.pexels.com/photos/4998306/pexels-photo-4998306.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '55-70°F',
    fruiting_time: '7-14 days',
    yield: 'Very High',
    substrate: 'Straw, coffee grounds, hardwood sawdust, paper waste',
    flavor_profile: 'Mild, slightly sweet with subtle woody notes',
  },
  {
    id: 'pink-oyster',
    name: 'Pink Oyster',
    description: 'Vibrant pink color that fades when cooked, fast grower',
    price: 18.99,
    difficulty: 'Beginner Friendly',
    image: 'https://images.pexels.com/photos/6044215/pexels-photo-6044215.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '75-85°F',
    fruiting_time: '7-10 days',
    yield: 'High',
    substrate: 'Straw, hardwood sawdust, coffee grounds',
    flavor_profile: 'Strong bacon-like flavor when cooked',
  },
  {
    id: 'phoenix-oyster',
    name: 'Phoenix Oyster',
    description: 'Heat-tolerant variety with beautiful grayish-brown caps',
    price: 19.99,
    difficulty: 'Beginner Friendly',
    image: 'https://images.pexels.com/photos/7583002/pexels-photo-7583002.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '65-85°F',
    fruiting_time: '10-14 days',
    yield: 'High',
    substrate: 'Straw, coffee grounds, hardwood sawdust',
    flavor_profile: 'Mild, typical oyster mushroom flavor',
  },
  {
    id: 'elm-oyster',
    name: 'Elm Oyster',
    description: 'Thick-fleshed oyster variety with nutty flavor',
    price: 19.99,
    difficulty: 'Beginner Friendly',
    image: 'https://images.pexels.com/photos/6044243/pexels-photo-6044243.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '60-75°F',
    fruiting_time: '10-21 days',
    yield: 'Medium',
    substrate: 'Hardwood sawdust, straw',
    flavor_profile: 'Nutty, slightly sweet with firm texture',
  },
  {
    id: 'king-oyster',
    name: 'King Oyster',
    description: 'Large thick stem with meaty texture, excellent for grilling',
    price: 21.99,
    difficulty: 'Intermediate',
    image: 'https://images.pexels.com/photos/8969237/pexels-photo-8969237.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '60-70°F',
    fruiting_time: '14-21 days',
    yield: 'Medium',
    substrate: 'Hardwood sawdust, supplemented sawdust',
    flavor_profile: 'Rich umami flavor with firm, meaty texture',
  },
  {
    id: 'maitake',
    name: 'Maitake',
    description: 'Also known as Hen of the Woods, feathery clusters with rich flavor',
    price: 24.99,
    difficulty: 'Advanced',
    image: 'https://images.pexels.com/photos/5501104/pexels-photo-5501104.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '60-70°F',
    fruiting_time: '14-21 days',
    yield: 'Medium-High',
    substrate: 'Hardwood sawdust, supplemented sawdust',
    flavor_profile: 'Rich, woodsy flavor with crunchy texture',
  },
  {
    id: 'morel',
    name: 'Morel',
    description: 'Highly prized wild mushroom with unique honeycomb cap',
    price: 29.99,
    difficulty: 'Expert',
    image: 'https://images.pexels.com/photos/13583784/pexels-photo-13583784.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '55-65°F',
    fruiting_time: '30-60 days',
    yield: 'Low',
    substrate: 'Complex outdoor beds, forest floor simulation',
    flavor_profile: 'Nutty, earthy, meaty with unique texture',
  },
  {
    id: 'chanterelle',
    name: 'Chanterelle',
    description: 'Golden trumpet-shaped wild mushroom with fruity aroma',
    price: 27.99,
    difficulty: 'Expert',
    image: 'https://images.pexels.com/photos/15027060/pexels-photo-15027060.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '60-65°F',
    fruiting_time: 'Seasonal',
    yield: 'Low',
    substrate: 'Mycorrhizal, requires tree symbiosis',
    flavor_profile: 'Fruity, apricot-like aroma with peppery notes',
  },
  {
    id: 'black-trumpet',
    name: 'Black Trumpet',
    description: 'Smoky flavor with thin, trumpet-shaped fruiting bodies',
    price: 26.99,
    difficulty: 'Expert',
    image: 'https://images.pexels.com/photos/4996288/pexels-photo-4996288.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '60-65°F',
    fruiting_time: 'Seasonal',
    yield: 'Low',
    substrate: 'Mycorrhizal, requires forest floor conditions',
    flavor_profile: 'Rich, smoky, deep flavor similar to black truffle',
  },
  {
    id: 'beech-mushroom',
    name: 'Beech Mushroom',
    description: 'Small clusters with buttery flavor and crunchy texture',
    price: 19.99,
    difficulty: 'Intermediate',
    image: 'https://images.pexels.com/photos/4997126/pexels-photo-4997126.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '60-70°F',
    fruiting_time: '14-21 days',
    yield: 'Medium-High',
    substrate: 'Beech wood, supplemented hardwood sawdust',
    flavor_profile: 'Mild, nutty, slightly sweet with firm texture',
  },
  {
    id: 'pioppino',
    name: 'Pioppino',
    description: 'Brown caps with long stems and complex flavor',
    price: 20.99,
    difficulty: 'Intermediate',
    image: 'https://images.pexels.com/photos/4997313/pexels-photo-4997313.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '55-70°F',
    fruiting_time: '14-21 days',
    yield: 'Medium',
    substrate: 'Hardwood sawdust, straw',
    flavor_profile: 'Rich, complex with notes of black tea and spice',
  },
  {
    id: 'enoki',
    name: 'Enoki',
    description: 'Long thin white stems with tiny caps, popular in Asian cuisine',
    price: 18.99,
    difficulty: 'Intermediate',
    image: 'https://images.pexels.com/photos/5590987/pexels-photo-5590987.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '40-55°F',
    fruiting_time: '30-40 days',
    yield: 'Medium',
    substrate: 'Hardwood sawdust, supplemented sawdust',
    flavor_profile: 'Mild, slightly fruity with crunchy texture',
  },
  {
    id: 'porcini',
    name: 'Porcini',
    description: 'Prized European mushroom with rich, meaty flavor',
    price: 28.99,
    difficulty: 'Expert',
    image: 'https://images.pexels.com/photos/6086929/pexels-photo-6086929.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '60-65°F',
    fruiting_time: 'Seasonal',
    yield: 'Low',
    substrate: 'Mycorrhizal, requires tree symbiosis',
    flavor_profile: 'Rich, meaty, nutty flavor intensifies when dried',
  },
  {
    id: 'chestnut-mushroom',
    name: 'Chestnut Mushroom',
    description: 'Brown capped variety with nutty flavor, similar to shiitake',
    price: 19.99,
    difficulty: 'Intermediate',
    image: 'https://images.pexels.com/photos/8469399/pexels-photo-8469399.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '60-70°F',
    fruiting_time: '14-21 days',
    yield: 'Medium-High',
    substrate: 'Hardwood sawdust, straw',
    flavor_profile: 'Nutty, earthy flavor with firm texture',
  },
  {
    id: 'wine-cap',
    name: 'Wine Cap',
    description: 'Burgundy-red caps that fade with age, outdoor garden variety',
    price: 21.99,
    difficulty: 'Beginner Friendly',
    image: 'https://images.pexels.com/photos/4996306/pexels-photo-4996306.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '55-75°F',
    fruiting_time: '60-90 days',
    yield: 'High',
    substrate: 'Wood chips, straw, garden beds',
    flavor_profile: 'Mild, nutty, potato-like flavor with firm texture',
  },
  {
    id: 'cauliflower-mushroom',
    name: 'Cauliflower Mushroom',
    description: 'Resembles cauliflower, excellent texture for culinary uses',
    price: 23.99,
    difficulty: 'Advanced',
    image: 'https://images.pexels.com/photos/17211392/pexels-photo-17211392/free-photo-of-coral-tooth-mushroom-growing-on-tree-trunk.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '60-70°F',
    fruiting_time: '21-30 days',
    yield: 'Medium',
    substrate: 'Hardwood logs, supplemented sawdust',
    flavor_profile: 'Mild, slightly nutty with excellent texture for pasta',
  },
  {
    id: 'paddy-straw',
    name: 'Paddy Straw Mushroom',
    description: 'Popular in Asian cuisine, thrives in tropical conditions',
    price: 20.99,
    difficulty: 'Intermediate',
    image: 'https://images.pexels.com/photos/4996249/pexels-photo-4996249.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '75-95°F',
    fruiting_time: '7-14 days',
    yield: 'High',
    substrate: 'Rice straw, cotton waste',
    flavor_profile: 'Mild, slightly sweet with tender texture',
  },
  {
    id: 'wood-blewit',
    name: 'Wood Blewit',
    description: 'Beautiful lilac-colored caps with spicy aroma',
    price: 22.99,
    difficulty: 'Advanced',
    image: 'https://images.pexels.com/photos/4996289/pexels-photo-4996289.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '45-60°F',
    fruiting_time: '30-45 days',
    yield: 'Medium',
    substrate: 'Leaf litter, compost, hardwood',
    flavor_profile: 'Complex, spicy, with a perfumed aroma',
  },
  {
    id: 'velvet-foot',
    name: 'Velvet Foot',
    description: 'Winter mushroom with velvety stem base, cold tolerant',
    price: 19.99,
    difficulty: 'Intermediate',
    image: 'https://images.pexels.com/photos/4997153/pexels-photo-4997153.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '40-60°F',
    fruiting_time: '14-28 days',
    yield: 'Medium',
    substrate: 'Hardwood, hardwood sawdust',
    flavor_profile: 'Mild, slightly sweet, firm texture when cooked',
  },
  {
    id: 'turkey-tail',
    name: 'Turkey Tail',
    description: 'Medicinal mushroom with multicolored fans, used for immunity',
    price: 21.99,
    difficulty: 'Beginner Friendly',
    image: 'https://images.pexels.com/photos/10209507/pexels-photo-10209507.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '60-75°F',
    fruiting_time: '60-90 days',
    yield: 'Low-Medium',
    substrate: 'Hardwood logs, supplemented sawdust',
    flavor_profile: 'Bitter, woody, not typically consumed as food',
  },
  {
    id: 'chaga',
    name: 'Chaga',
    description: 'Medicinal mushroom that grows on birch trees, used for tea',
    price: 26.99,
    difficulty: 'Expert',
    image: 'https://images.pexels.com/photos/6112359/pexels-photo-6112359.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '55-75°F',
    fruiting_time: 'Years',
    yield: 'Very Low',
    substrate: 'Living birch trees',
    flavor_profile: 'Bitter, earthy, vanilla notes, used for tea not food',
  },
  {
    id: 'reishi',
    name: 'Reishi',
    description: 'Ancient medicinal mushroom used for immune support',
    price: 24.99,
    difficulty: 'Intermediate',
    image: 'https://images.pexels.com/photos/5799636/pexels-photo-5799636.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '70-85°F',
    fruiting_time: '60-180 days',
    yield: 'Medium',
    substrate: 'Hardwood logs, supplemented sawdust',
    flavor_profile: 'Very bitter, woody, used for tea not food',
  },
  {
    id: 'cordyceps',
    name: 'Cordyceps',
    description: 'Treasured medicinal mushroom used for energy and endurance',
    price: 29.99,
    difficulty: 'Advanced',
    image: 'https://images.pexels.com/photos/3039671/pexels-photo-3039671.jpeg?auto=compress&cs=tinysrgb&w=800',
    growing_temp: '65-75°F',
    fruiting_time: '60-90 days',
    yield: 'Low',
    substrate: 'Specialized grain media',
    flavor_profile: 'Mild, slightly bitter, usually consumed as extract',
  },
];

// Product categories
export const PRODUCT_CATEGORIES = [
  { id: "all", name: "All Products" },
  { id: "growing-kits", name: "Growing Kits" },
  { id: "equipment", name: "Equipment" },
  { id: "substrates", name: "Substrates" },
  { id: "cultures", name: "Cultures & Spores" },
  { id: "books", name: "Books & Education" },
  { id: "subscriptions", name: "Subscriptions" },
];

// Featured products
export const FEATURED_PRODUCTS = [
  {
    id: 'growing-kit',
    name: 'Complete Growing Kit',
    description: 'Everything you need to start growing gourmet mushrooms at home',
    price: 49.99,
    image: 'https://images.pexels.com/photos/6044266/pexels-photo-6044266.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'growing-kits',
    featured: true,
  },
  {
    id: 'humidity-controller',
    name: 'Humidity Controller',
    description: 'Professional-grade humidity control for optimal growing conditions',
    price: 79.99,
    image: 'https://images.pexels.com/photos/7262897/pexels-photo-7262897.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'equipment',
    featured: true,
  },
  {
    id: 'organic-substrate',
    name: 'Organic Substrate',
    description: 'Premium organic substrate for healthy, abundant mushroom growth',
    price: 24.99,
    image: 'https://images.pexels.com/photos/4996302/pexels-photo-4996302.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'substrates',
    featured: true,
  },
  {
    id: 'monthly-culture-box',
    name: 'Monthly Culture Box',
    description: 'Subscription service with new cultures, tools, and growing tips',
    price: 39.99,
    subscription: true,
    image: 'https://images.pexels.com/photos/4218662/pexels-photo-4218662.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'subscriptions',
    featured: true,
  },
];

// All products
export const ALL_PRODUCTS = [
  ...FEATURED_PRODUCTS,
  {
    id: 'beginners-oyster-kit',
    name: 'Beginner\'s Oyster Mushroom Kit',
    description: 'Perfect starter kit for first-time growers, includes Blue Oyster culture',
    price: 34.99,
    image: 'https://images.pexels.com/photos/6044283/pexels-photo-6044283.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'growing-kits',
  },
  {
    id: 'advanced-growers-kit',
    name: 'Advanced Grower\'s Kit',
    description: 'Complete setup for experienced growers, includes multiple culture options',
    price: 89.99,
    image: 'https://images.pexels.com/photos/8128298/pexels-photo-8128298.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'growing-kits',
  },
  {
    id: 'shiitake-log-kit',
    name: 'Shiitake Log Growing Kit',
    description: 'Traditional log cultivation kit with pre-inoculated hardwood',
    price: 44.99,
    image: 'https://images.pexels.com/photos/1459339/pexels-photo-1459339.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'growing-kits',
  },
  {
    id: 'lions-mane-kit',
    name: 'Lion\'s Mane Growing Kit',
    description: 'Specialized kit for growing this medicinal and culinary mushroom at home',
    price: 39.99,
    image: 'https://images.pexels.com/photos/6044197/pexels-photo-6044197.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'growing-kits',
  },
  {
    id: 'temperature-controller',
    name: 'Digital Temperature Controller',
    description: 'Precise temperature regulation for optimal mycelium growth',
    price: 69.99,
    image: 'https://images.pexels.com/photos/3884866/pexels-photo-3884866.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'equipment',
  },
  {
    id: 'fruiting-chamber',
    name: 'Automated Fruiting Chamber',
    description: 'Complete environment control for perfect fruiting conditions',
    price: 199.99,
    image: 'https://images.pexels.com/photos/1105019/pexels-photo-1105019.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'equipment',
  },
  {
    id: 'pressure-cooker',
    name: '23-Quart Pressure Cooker',
    description: 'Essential tool for sterilizing substrate and creating clean spawn',
    price: 129.99,
    image: 'https://images.pexels.com/photos/8774522/pexels-photo-8774522.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'equipment',
  },
  {
    id: 'laminar-flow-hood',
    name: 'Laminar Flow Hood',
    description: 'Professional-grade clean air workstation for sterile procedures',
    price: 349.99,
    image: 'https://images.pexels.com/photos/5726837/pexels-photo-5726837.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'equipment',
  },
  {
    id: 'ultrasonic-humidifier',
    name: 'Ultrasonic Humidifier',
    description: 'High-output humidity generation for fruiting chambers',
    price: 59.99,
    image: 'https://images.pexels.com/photos/4021262/pexels-photo-4021262.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'equipment',
  },
  {
    id: 'hardwood-sawdust',
    name: 'Premium Hardwood Sawdust',
    description: '10lb bag of sterilized oak sawdust for wood-loving species',
    price: 19.99,
    image: 'https://images.pexels.com/photos/6044271/pexels-photo-6044271.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'substrates',
  },
  {
    id: 'coco-coir',
    name: 'Coconut Coir Substrate',
    description: 'Eco-friendly growing medium perfect for various mushroom species',
    price: 14.99,
    image: 'https://images.pexels.com/photos/7657503/pexels-photo-7657503.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'substrates',
  },
  {
    id: 'straw-substrate',
    name: 'Pasteurized Wheat Straw',
    description: 'Ready-to-use straw substrate, ideal for oyster varieties',
    price: 17.99,
    image: 'https://images.pexels.com/photos/6044245/pexels-photo-6044245.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'substrates',
  },
  {
    id: 'masters-mix',
    name: 'Master\'s Mix Premium Substrate',
    description: 'Professional blend of hardwood sawdust and soy hulls',
    price: 29.99,
    image: 'https://images.pexels.com/photos/6044267/pexels-photo-6044267.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'substrates',
  },
  {
    id: 'grain-spawn',
    name: 'Sterilized Grain Spawn Bags',
    description: 'Pre-sterilized rye berries ready for inoculation',
    price: 22.99,
    image: 'https://images.pexels.com/photos/4997123/pexels-photo-4997123.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'substrates',
  },
  {
    id: 'petri-dishes',
    name: 'Pre-poured Agar Plates',
    description: 'Sterile malt extract agar plates for culture work',
    price: 15.99,
    image: 'https://images.pexels.com/photos/3735704/pexels-photo-3735704.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'cultures',
  },
  {
    id: 'liquid-culture-kit',
    name: 'Liquid Culture Kit',
    description: 'Complete setup for creating and maintaining liquid cultures',
    price: 34.99,
    image: 'https://images.pexels.com/photos/7262909/pexels-photo-7262909.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'cultures',
  },
  {
    id: 'culture-syringes',
    name: 'Culture Syringes 5-Pack',
    description: 'Assorted gourmet mushroom cultures in sterile syringes',
    price: 49.99,
    image: 'https://images.pexels.com/photos/4210605/pexels-photo-4210605.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'cultures',
  },
  {
    id: 'oyster-variety-pack',
    name: 'Oyster Mushroom Variety Pack',
    description: 'Collection of 5 different oyster mushroom cultures',
    price: 59.99,
    image: 'https://images.pexels.com/photos/5799680/pexels-photo-5799680.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'cultures',
  },
  {
    id: 'medicinal-variety-pack',
    name: 'Medicinal Mushroom Culture Pack',
    description: 'Includes cultures of Reishi, Turkey Tail, and Lion\'s Mane',
    price: 64.99,
    image: 'https://images.pexels.com/photos/5799636/pexels-photo-5799636.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'cultures',
  },
  {
    id: 'beginners-guide',
    name: 'The Complete Mushroom Grower\'s Guide',
    description: 'Comprehensive guidebook for home cultivation',
    price: 29.99,
    image: 'https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'books',
  },
  {
    id: 'advanced-techniques',
    name: 'Advanced Cultivation Techniques',
    description: 'Detailed book covering advanced methods and problem-solving',
    price: 34.99,
    image: 'https://images.pexels.com/photos/3747139/pexels-photo-3747139.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'books',
  },
  {
    id: 'video-course',
    name: 'Video Course: From Spore to Harvest',
    description: 'Complete digital course with step-by-step video instructions',
    price: 79.99,
    image: 'https://images.pexels.com/photos/4050315/pexels-photo-4050315.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'books',
  },
  {
    id: 'medicinal-mushrooms-guide',
    name: 'Medicinal Mushrooms: Growing and Usage Guide',
    description: 'In-depth guide to growing and using mushrooms for health',
    price: 32.99,
    image: 'https://images.pexels.com/photos/1870438/pexels-photo-1870438.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'books',
  },
  {
    id: 'beginners-subscription',
    name: 'Beginner\'s Monthly Subscription',
    description: 'Monthly delivery of easy-to-grow cultures and supplies',
    price: 29.99,
    subscription: true,
    image: 'https://images.pexels.com/photos/4218662/pexels-photo-4218662.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'subscriptions',
  },
  {
    id: 'premium-subscription',
    name: 'Premium Grower\'s Subscription',
    description: 'Monthly package with rare cultures and professional supplies',
    price: 49.99,
    subscription: true,
    image: 'https://images.pexels.com/photos/6044191/pexels-photo-6044191.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'subscriptions',
  },
  {
    id: 'quarterly-bulk',
    name: 'Quarterly Bulk Subscription',
    description: 'Large shipment of supplies every 3 months for serious growers',
    price: 129.99,
    subscription: true,
    image: 'https://images.pexels.com/photos/6044275/pexels-photo-6044275.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'subscriptions',
  },
];

// Growing guides
export const GROWING_GUIDES = [
  {
    id: 'beginners-guide',
    title: 'Beginner\'s Guide to Mushroom Cultivation',
    category: 'beginner',
    excerpt: 'A comprehensive introduction to home mushroom growing for complete beginners',
    content: 'This guide covers all the basics you need to know to start growing mushrooms at home, including equipment needed, environment setup, and step-by-step instructions.',
    image: 'https://images.pexels.com/photos/6044266/pexels-photo-6044266.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2023-05-15',
    readTime: '10 min',
    tags: ['beginner', 'basics', 'introduction'],
  },
  {
    id: 'oyster-cultivation',
    title: 'Cultivating Oyster Mushrooms',
    category: 'species-specific',
    excerpt: 'Step-by-step guide for growing different oyster mushroom varieties',
    content: 'Learn how to grow Pearl, Blue, Pink, Golden, and King Oyster mushrooms with detailed instructions for each variety and their specific requirements.',
    image: 'https://images.pexels.com/photos/5799654/pexels-photo-5799654.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2023-06-22',
    readTime: '15 min',
    tags: ['oyster', 'species-specific', 'intermediate'],
  },
  {
    id: 'shiitake-log-cultivation',
    title: 'Traditional Shiitake Log Cultivation',
    category: 'techniques',
    excerpt: 'Master the traditional method of growing shiitake mushrooms on logs',
    content: 'Learn the centuries-old technique of growing shiitake mushrooms on hardwood logs, including selecting logs, inoculation methods, and long-term maintenance.',
    image: 'https://images.pexels.com/photos/1627825/pexels-photo-1627825.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2023-07-10',
    readTime: '12 min',
    tags: ['shiitake', 'logs', 'traditional', 'intermediate'],
  },
  {
    id: 'lions-mane-cultivation',
    title: 'Lion\'s Mane Cultivation Guide',
    category: 'species-specific',
    excerpt: 'Complete guide to growing this unique medicinal and culinary mushroom',
    content: 'Learn how to successfully grow Lion\'s Mane mushrooms with information on substrate preparation, fruiting conditions, and common challenges.',
    image: 'https://images.pexels.com/photos/6044197/pexels-photo-6044197.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2023-08-05',
    readTime: '14 min',
    tags: ['lion\'s mane', 'medicinal', 'intermediate'],
  },
  {
    id: 'substrate-preparation',
    title: 'Substrate Preparation and Sterilization',
    category: 'techniques',
    excerpt: 'Learn the critical process of preparing and sterilizing substrate',
    content: 'This guide covers various substrate materials, preparation methods, and sterilization techniques to ensure successful mushroom cultivation.',
    image: 'https://images.pexels.com/photos/4996302/pexels-photo-4996302.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2023-09-18',
    readTime: '20 min',
    tags: ['substrate', 'sterilization', 'intermediate', 'technical'],
  },
  {
    id: 'agar-cultivation',
    title: 'Working with Agar: Culture Maintenance and Expansion',
    category: 'advanced',
    excerpt: 'Advanced techniques for working with mushroom cultures on agar',
    content: 'Learn how to work with agar to isolate, expand, and maintain mushroom cultures with step-by-step instructions for preparing plates and sterile techniques.',
    image: 'https://images.pexels.com/photos/3735704/pexels-photo-3735704.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2023-10-12',
    readTime: '25 min',
    tags: ['agar', 'cultures', 'advanced', 'technical'],
  },
  {
    id: 'fruiting-chamber-setup',
    title: 'Building and Maintaining Fruiting Chambers',
    category: 'equipment',
    excerpt: 'How to create the perfect environment for mushroom fruiting',
    content: 'This guide covers different designs for fruiting chambers, from simple setups to automated systems, with instructions for maintaining optimal conditions.',
    image: 'https://images.pexels.com/photos/1105019/pexels-photo-1105019.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2023-11-05',
    readTime: '18 min',
    tags: ['fruiting', 'equipment', 'intermediate', 'environment'],
  },
  {
    id: 'medicinal-mushroom-growing',
    title: 'Growing Medicinal Mushrooms: Reishi, Turkey Tail, and Cordyceps',
    category: 'medicinal',
    excerpt: 'Guide to cultivating mushrooms valued for their health benefits',
    content: 'Learn specific techniques for growing medicinal mushroom species with information on their unique cultivation requirements and considerations.',
    image: 'https://images.pexels.com/photos/5799636/pexels-photo-5799636.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2023-12-20',
    readTime: '22 min',
    tags: ['medicinal', 'reishi', 'turkey tail', 'cordyceps', 'advanced'],
  },
  {
    id: 'troubleshooting-guide',
    title: 'Troubleshooting Common Cultivation Problems',
    category: 'troubleshooting',
    excerpt: 'Solutions for the most common issues faced by mushroom growers',
    content: 'This comprehensive guide helps identify and solve common problems in mushroom cultivation, from contamination to improper fruiting conditions.',
    image: 'https://images.pexels.com/photos/4996283/pexels-photo-4996283.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2024-01-15',
    readTime: '30 min',
    tags: ['troubleshooting', 'problems', 'contamination', 'all-levels'],
  },
  {
    id: 'outdoor-mushroom-beds',
    title: 'Creating Outdoor Mushroom Gardens',
    category: 'outdoor',
    excerpt: 'How to establish productive outdoor mushroom growing areas',
    content: 'Learn how to create and maintain outdoor mushroom beds and gardens using wood chips, straw, and other materials for seasonal harvests.',
    image: 'https://images.pexels.com/photos/1643402/pexels-photo-1643402.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2024-02-10',
    readTime: '16 min',
    tags: ['outdoor', 'garden', 'intermediate', 'seasonal'],
  },
  {
    id: 'gourmet-mushroom-recipes',
    title: 'Cooking with Home-Grown Gourmet Mushrooms',
    category: 'culinary',
    excerpt: 'Delicious recipes to showcase your mushroom harvests',
    content: 'A collection of recipes specifically designed to highlight the flavors and textures of different gourmet mushroom varieties you can grow at home.',
    image: 'https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2024-03-05',
    readTime: '12 min',
    tags: ['recipes', 'cooking', 'culinary', 'all-levels'],
  },
  {
    id: 'spawn-production',
    title: 'Mastering Spawn Production',
    category: 'advanced',
    excerpt: 'Advanced guide to creating different types of mushroom spawn',
    content: 'Learn how to produce grain spawn, sawdust spawn, and liquid cultures with focus on maintaining sterility and maximizing colonization rates.',
    image: 'https://images.pexels.com/photos/4997123/pexels-photo-4997123.jpeg?auto=compress&cs=tinysrgb&w=800',
    publishDate: '2024-04-18',
    readTime: '28 min',
    tags: ['spawn', 'advanced', 'technical', 'sterile technique'],
  },
];

// Growing guide categories
export const GUIDE_CATEGORIES = [
  { id: "all", name: "All Guides" },
  { id: "beginner", name: "Beginner Guides" },
  { id: "species-specific", name: "Species Guides" },
  { id: "techniques", name: "Techniques" },
  { id: "equipment", name: "Equipment" },
  { id: "advanced", name: "Advanced Topics" },
  { id: "medicinal", name: "Medicinal Mushrooms" },
  { id: "outdoor", name: "Outdoor Growing" },
  { id: "troubleshooting", name: "Troubleshooting" },
  { id: "culinary", name: "Cooking & Recipes" },
];

// Culture difficulty levels
export const DIFFICULTY_LEVELS = [
  { id: "all", name: "All Difficulty Levels" },
  { id: "Beginner Friendly", name: "Beginner Friendly" },
  { id: "Intermediate", name: "Intermediate" },
  { id: "Advanced", name: "Advanced" },
  { id: "Expert", name: "Expert" },
];

// Testimonials
export const TESTIMONIALS = [
  {
    id: 1,
    content: '"I was hesitant to grow my own mushrooms, but Frontier Fungi\'s beginner kit made it so simple! The step-by-step instructions were clear, and I had my first harvest of Blue Oysters within weeks. Now I\'m hooked!"',
    author: {
      name: 'Jessica D.',
      role: 'Home Grower',
      initials: 'JD',
    },
    rating: 5,
  },
  {
    id: 2,
    content: '"The StamBot AI assistant is a game-changer! When my Lion\'s Mane started showing unusual growth patterns, I uploaded photos and got immediate advice that saved my harvest. Worth every penny of the premium subscription."',
    author: {
      name: 'Mark T.',
      role: 'Chef & Grower',
      initials: 'MT',
    },
    rating: 5,
  },
  {
    id: 3,
    content: '"I\'ve been ordering from Frontier Fungi for over a year now. Their monthly subscription keeps me trying new varieties I wouldn\'t have discovered otherwise. The quality is consistently excellent, and their customer service is top-notch."',
    author: {
      name: 'Anna K.',
      role: 'Culinary Enthusiast',
      initials: 'AK',
    },
    rating: 5,
  },
];

// Social gallery images
export const SOCIAL_GALLERY_IMAGES = [
  {
    id: 1,
    alt: 'Golden oyster mushroom harvest',
    src: 'https://images.pexels.com/photos/5799654/pexels-photo-5799654.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 2,
    alt: 'Home mushroom growing setup',
    src: 'https://images.pexels.com/photos/6044283/pexels-photo-6044283.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 3,
    alt: 'Chef cooking with fresh mushrooms',
    src: 'https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 4,
    alt: 'Lion\'s mane mushroom closeup',
    src: 'https://images.pexels.com/photos/6044197/pexels-photo-6044197.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 5,
    alt: 'Basket of wild mushrooms',
    src: 'https://images.pexels.com/photos/1643402/pexels-photo-1643402.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 6,
    alt: 'Mushroom mycelium growth',
    src: 'https://images.pexels.com/photos/6044282/pexels-photo-6044282.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
];

// Footer links
export const FOOTER_LINKS = {
  shop: [
    { name: 'Growing Kits', href: '#' },
    { name: 'Mushroom Cultures', href: '#' },
    { name: 'Cultivation Supplies', href: '#' },
    { name: 'Monthly Subscriptions', href: '#' },
    { name: 'Gift Cards', href: '#' },
  ],
  learn: [
    { name: 'Growing Guides', href: '#' },
    { name: 'Video Tutorials', href: '#' },
    { name: 'Mushroom Species', href: '#' },
    { name: 'FAQ', href: '#' },
    { name: 'Blog', href: '#' },
  ],
  company: [
    { name: 'About Us', href: '#' },
    { name: 'Sustainability', href: '#' },
    { name: 'Contact', href: '#' },
    { name: 'Careers', href: '#' },
    { name: 'Press', href: '#' },
  ],
  legal: [
    { name: 'Privacy Policy', href: '#' },
    { name: 'Terms of Service', href: '#' },
    { name: 'Shipping', href: '#' },
    { name: 'Returns', href: '#' },
  ],
};
